# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNI18n' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNI18n

  target 'RNI18nTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
